import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        {/* toaster  */}
        <Toaster
          position="top-center"
          toastOptions={{
            style: {
              background: '#393939ff',
              color: '#fff',
              fontSize: '14px',
              borderRadius: '10px',
              padding: '5px 10px',
            },
          }}
        />

        {/* childrens   */}
        {children}
      </body>
    </html>
  );
}
