import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/src/style/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// loader and toaster
import { Toaster } from "react-hot-toast";
import NextTopLoader from "nextjs-toploader";

// components 
import StoreUser from "../components/StoreUser";

// redux 
import { ReduxProvider } from "../lib/ReduxProvider";
import TanstackQueryProvider from "../providers/tanstack-query-provider";

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#f6f5f8]`}
      >
        {/* tansctack provider  */}
        <TanstackQueryProvider>

          {/* redux provider  */}
          <ReduxProvider>

            {/* store user  */}
            <StoreUser />

            {/* toaster  */}
            <Toaster
              position="top-center"
              toastOptions={{
                style: {
                  background: '#393939ff',
                  color: '#fff',
                  fontSize: '14px',
                  borderRadius: '10px',
                  padding: '5px 10px',
                },
              }}
            />

            {/* top loader  */}
            <NextTopLoader color="#7f22fe" />

            {/* childrens   */}
            {children}

            {/* redux provider end */}
          </ReduxProvider>

        </TanstackQueryProvider>
      </body>
    </html>
  );
}
